### ISSUE TITLE
Getting class structure

### ISSUE THREAD

**Issue by manishgurnaney** [fabiantheblind/ask-me-anything#1]
Hi Fabian, 
          I am working on getting the json structure of an AET file. Like get the components and what all properties are set in a component. So just getting confused how to start in that.

**Comment by ff6347** [comment]
What is in aet? After effects template? I never took a peak into them. What is confusing you?

**Comment by manishgurnaney** [comment]
Aet is After effects Template file. It has a certain comp layers in the Main Composition with some properties modified like Position, Scalling or Opacity. 
So Is there any what from where i can get which properties are modified.

**Comment by ff6347** [comment]
Puh. I really don't know. There might be some scripts like open sesame do an export of projects. I can't imagine that they export all the properties

**Comment by manishgurnaney** [comment]
Ok, Thanks for your time. I will check if I found something will paste here in the Issue  ID

**Comment by ff6347** [comment]
Cool.
